### ISSUE TITLE
100x slower on Ubuntu

### ISSUE THREAD

**Issue by eric-burel** [bellockk/alphashape#15]
* Alpha Shape Toolbox version: alphashape==1.0.2
* Python version: 3.7
* Operating System: Ubuntu 18.04

Also Numpy version: numpy==1.16.3

### Description

Alphashape.alphashape is taking a few seconds to compute for an alpha hull of 0.1 and thousands of points.
However, it seems around a hundred times faster on Windows.

I am working on a reproduction with clearer measurements, but in the meantime, do you have any tip what I could do to investigate the issue or what info I could provide to help?

Is there a specific computation that could provoke some slowness, eg some intensive computation that rely specifically on Numpy or any other 3rd party lib to be performant, or anything like that?

### What I Expected

Same perfs on Windows and Linux

**Comment by bellockk** [comment]
Could you try profiling the code while running with your data set on both platforms?  That might point to the code that is causing the difference in speed.  Also, is there any chance you installed a numpy compiled with intel's mkl on windows and without on linux?

**Comment by eric-burel** [comment]
I think we solved an algorithmic issue in the code, and the issue disappeared. I do'nt have more info so I will close, I was the one experiencing the issue but not the actual coder so sorry I have only very partial information.
