### ISSUE TITLE
Citation for code?

### ISSUE THREAD

**Issue by evanseitz** [bellockk/alphashape#19]
I intend to cite your work in a paper I am writing, in which this code is being used. Could you possibly provide a Zenodo link or some other kind of citation information somewhere in your readme (and here)?

**Comment by bellockk** [comment]
A Zenodo link is now available for citing this work.
https://zenodo.org/record/4603211#.YEz8Xu1KiV5

**Comment by evanseitz** [comment]
Thank you.

**Comment by Husky-H** [comment]
> A Zenodo link is now available for citing this work. https://zenodo.org/record/4603211#.YEz8Xu1KiV5

I'sorry, the website seems to be invalid, can you cheek it, thank you.
